module.exports = {
    SHOW_ADD_PRODUCT_MODAL: 'SHOW_ADD_PRODUCT_MODAL',       //products constants
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_PRODUCT: 'GET_PRODUCT',
    CHANGE_PRODUCT: 'CHANGE_PRODUCT',
    ADD_PRODUCT: 'ADD_PRODUCT',
    GET_COMMENTS: 'GET_COMMENTS',
    POST_COMMENT: 'POST_COMMENT',
    DELETE_COMMENT: 'DELETE_COMMENT',
    CLEAN_PRODUCT: 'CLEAN_PRODUCT',
    CLEAN_PRODUCTS: 'CLEAN_PRODUCTS',
    CHANGE_AVAILABLE: 'CHANGE_AVAILABLE',
    CHANGE_PAGE: 'CHANGE_PAGE',
    CHANGE_SORT: 'CHANGE_SORT',
    CHANGE_PAGES: 'CHANGE_PAGES',

    LOGIN: 'LOGIN',                                         //profile constants
    LOGOUT: 'LOGOUT',
    SIGN_UP : 'SIGN_UP',
    SHOW_LOGIN: 'SHOW_LOGIN',
    SHOW_SIGN_UP: 'SHOW_SIGN_UP',
    GET_PROFILE_ORDERS: 'GET_PROFILE_ORDERS',
    CHANGE_PROFILE: 'CHANGE_PROFILE',
    SHOW_CHANGE_PASSWORD: 'SHOW_CHANGE_PASSWORD',
    TO_FAVORITES : 'TO_FAVORITES',
    FROM_FAVORITES : 'FROM_FAVORITES',

    TO_CART: 'TO_CART',                                     //cart constants
    FROM_CART: 'FROM_CART',
    ADD_IN_CART: 'ADD_IN_CART',
    SUBTRACT_IN_CART: 'SUBTRACT_IN_CART',
    SHOW_CART: 'SHOW_CART',

    CONFIRM_ORDER: 'CONFIRM_ORDER',                         //order constants
    GET_ORDERS_LIST: 'GET_ORDERS_LIST',
    CHANGE_ORDER_STATE: 'CHANGE_ORDER_STATE',

    GET_CLIENTS: 'GET_CLIENTS',                             //clients constants
    BLOCK_CLIENT: 'BLOCK_CLIENT',
    GET_CLIENT_HISTORY: 'GET_CLIENT_HISTORY',
    CLEAN_HISTORY: 'CLEAN_HISTORY',
    SHOW_CLIENT_MODAL: 'SHOW_CLIENT_MODAL',
    HIDE_CLIENT_MODAL: 'HIDE_CLIENT_MODAL'
};