module.exports = {
    SHOW_ADD_PRODUCT_MODAL : 'SHOW_ADD_PRODUCT_MODAL',
    GET_PRODUCTS : 'GET_PRODUCTS',
    GET_PRODUCT : 'GET_PRODUCT',
    CHANGE_PRODUCT : 'CHANGE_PRODUCT',
    ADD_PRODUCT : 'ADD_PRODUCT',
    GET_COMMENTS : 'GET_COMMENTS',
    POST_COMMENT : 'POST_COMMENT',
    DELETE_COMMENT : 'DELETE_COMMENT',
    
    GET_USERS : 'GET_USERS',
    GET_USER : 'GET_USER',
    LOGIN : 'LOGIN',
    LOGOUT : 'LOGOUT',
    SHOW_LOGIN : 'SHOW_LOGIN',


    TO_CART : 'TO_CART',
    FROM_CART : 'FROM_CART',
    ADD_IN_CART : 'ADD_IN_CART',
    SUBTRACT_IN_CART : 'SUBTRACT_IN_CART',
    SHOW_CART : 'SHOW_CART',

    CONFIRM_ORDER : 'CONFIRM_ORDER',
    GET_ORDERS_LIST : 'GET_ORDERS_LIST',
    GET_USER_ORDERS : 'GET_USER_ORDERS'
};